package com.jp.login.mapper;

import com.jp.login.entity.ContentItem;
import com.jp.login.entity.ContentItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ContentItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_items
     *
     * @mbg.generated
     */
    long countByExample(ContentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_items
     *
     * @mbg.generated
     */
    int deleteByExample(ContentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_items
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_items
     *
     * @mbg.generated
     */
    int insert(ContentItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_items
     *
     * @mbg.generated
     */
    int insertSelective(ContentItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_items
     *
     * @mbg.generated
     */
    List<ContentItem> selectByExample(ContentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_items
     *
     * @mbg.generated
     */
    ContentItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_items
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ContentItem row, @Param("example") ContentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_items
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ContentItem row, @Param("example") ContentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ContentItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content_items
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ContentItem row);
}