package com.jp.login.mapper;

import com.jp.login.entity.MstUser;
import com.jp.login.entity.MstUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MstUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated
     */
    long countByExample(MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated
     */
    int deleteByExample(MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated
     */
    int insert(MstUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated
     */
    int insertSelective(MstUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated
     */
    List<MstUser> selectByExample(MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated
     */
    MstUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MstUser row, @Param("example") MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MstUser row, @Param("example") MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MstUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MstUser row);
}