package com.jp.login.mapper;

import com.jp.login.entity.WebauthnCredentials;
import com.jp.login.entity.WebauthnCredentialsExample;
import com.jp.login.entity.WebauthnCredentialsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WebauthnCredentialsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    long countByExample(WebauthnCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    int deleteByExample(WebauthnCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(byte[] credentialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    int insert(WebauthnCredentialsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    int insertSelective(WebauthnCredentialsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    List<WebauthnCredentialsWithBLOBs> selectByExampleWithBLOBs(WebauthnCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    List<WebauthnCredentials> selectByExample(WebauthnCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    WebauthnCredentialsWithBLOBs selectByPrimaryKey(byte[] credentialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") WebauthnCredentialsWithBLOBs row, @Param("example") WebauthnCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") WebauthnCredentialsWithBLOBs row, @Param("example") WebauthnCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") WebauthnCredentials row, @Param("example") WebauthnCredentialsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WebauthnCredentialsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(WebauthnCredentialsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WebauthnCredentials row);
}