spring:
  application:
    name: local
  session:
    timeout: 300
  profiles:
    active: h2
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  compression:
    enabled: true
