spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/home?useSSL=false&allowPublicKeyRetrieval=true
    username: ARISTOS
    password: ARISTOSPASS
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  compression:
    enabled: true