spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/home?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    session:
      timeout: 1m
  mybatis:
    type-aliases-package: com.example.demo.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
logging:
  level:
    #    org.apache.ibatis: DEBUG
    java.sql: TRACE
    #    org.springframework.security: DEBUG
    org.mybatis: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE