spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
    enabled: true
  datasource:
    url: jdbc:mysql://192.168.3.18:3306/home?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver