spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    check-template: false
    check-template-location: false
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/home?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    session:
      timeout: 1m
  mybatis:
    type-aliases-package: com.example.demo.entity
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true