package com.jp.login.entity;

import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table content_items
 */
@Data
public class ContentItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_items.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_items.item_name
     *
     * @mbg.generated
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_items.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_items.updated_at
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;
}