package com.jp.login.entity;

import java.time.LocalDateTime;
import lombok.Data;

@Data
public class ContentItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_items.id
     *
     * @mbg.generated Sun Sep 07 16:02:13 JST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_items.item_name
     *
     * @mbg.generated Sun Sep 07 16:02:13 JST 2025
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_items.created_at
     *
     * @mbg.generated Sun Sep 07 16:02:13 JST 2025
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content_items.updated_at
     *
     * @mbg.generated Sun Sep 07 16:02:13 JST 2025
     */
    private LocalDateTime updatedAt;
}