package com.jp.login.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mst_user
 */
@Data
public class MstUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.discord_name
     *
     * @mbg.generated
     */
    private String discordName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.password_expiry_date
     *
     * @mbg.generated
     */
    private LocalDate passwordExpiryDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.credentials_non_expired
     *
     * @mbg.generated
     */
    private LocalDate credentialsNonExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.account_non_expired
     *
     * @mbg.generated
     */
    private LocalDate accountNonExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.discord_status
     *
     * @mbg.generated
     */
    private Boolean discordStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.enabled
     *
     * @mbg.generated
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.role
     *
     * @mbg.generated
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.account_non_locked
     *
     * @mbg.generated
     */
    private Boolean accountNonLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_user.updated_at
     *
     * @mbg.generated
     */
    private LocalDateTime updatedAt;
}