package com.jp.login.entity;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table webauthn_credentials
 */
@Data
public class WebauthnCredentials {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webauthn_credentials.credential_id
     *
     * @mbg.generated
     */
    private byte[] credentialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webauthn_credentials.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webauthn_credentials.sign_count
     *
     * @mbg.generated
     */
    private Long signCount;
}