package com.jp.login.entity;

import java.util.ArrayList;
import java.util.List;

public class WebauthnCredentialsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    public WebauthnCredentialsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCredentialIdIsNull() {
            addCriterion("credential_id is null");
            return (Criteria) this;
        }

        public Criteria andCredentialIdIsNotNull() {
            addCriterion("credential_id is not null");
            return (Criteria) this;
        }

        public Criteria andCredentialIdEqualTo(byte[] value) {
            addCriterion("credential_id =", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdNotEqualTo(byte[] value) {
            addCriterion("credential_id <>", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdGreaterThan(byte[] value) {
            addCriterion("credential_id >", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdGreaterThanOrEqualTo(byte[] value) {
            addCriterion("credential_id >=", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdLessThan(byte[] value) {
            addCriterion("credential_id <", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdLessThanOrEqualTo(byte[] value) {
            addCriterion("credential_id <=", value, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdIn(List<byte[]> values) {
            addCriterion("credential_id in", values, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdNotIn(List<byte[]> values) {
            addCriterion("credential_id not in", values, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdBetween(byte[] value1, byte[] value2) {
            addCriterion("credential_id between", value1, value2, "credentialId");
            return (Criteria) this;
        }

        public Criteria andCredentialIdNotBetween(byte[] value1, byte[] value2) {
            addCriterion("credential_id not between", value1, value2, "credentialId");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andSignCountIsNull() {
            addCriterion("sign_count is null");
            return (Criteria) this;
        }

        public Criteria andSignCountIsNotNull() {
            addCriterion("sign_count is not null");
            return (Criteria) this;
        }

        public Criteria andSignCountEqualTo(Long value) {
            addCriterion("sign_count =", value, "signCount");
            return (Criteria) this;
        }

        public Criteria andSignCountNotEqualTo(Long value) {
            addCriterion("sign_count <>", value, "signCount");
            return (Criteria) this;
        }

        public Criteria andSignCountGreaterThan(Long value) {
            addCriterion("sign_count >", value, "signCount");
            return (Criteria) this;
        }

        public Criteria andSignCountGreaterThanOrEqualTo(Long value) {
            addCriterion("sign_count >=", value, "signCount");
            return (Criteria) this;
        }

        public Criteria andSignCountLessThan(Long value) {
            addCriterion("sign_count <", value, "signCount");
            return (Criteria) this;
        }

        public Criteria andSignCountLessThanOrEqualTo(Long value) {
            addCriterion("sign_count <=", value, "signCount");
            return (Criteria) this;
        }

        public Criteria andSignCountIn(List<Long> values) {
            addCriterion("sign_count in", values, "signCount");
            return (Criteria) this;
        }

        public Criteria andSignCountNotIn(List<Long> values) {
            addCriterion("sign_count not in", values, "signCount");
            return (Criteria) this;
        }

        public Criteria andSignCountBetween(Long value1, Long value2) {
            addCriterion("sign_count between", value1, value2, "signCount");
            return (Criteria) this;
        }

        public Criteria andSignCountNotBetween(Long value1, Long value2) {
            addCriterion("sign_count not between", value1, value2, "signCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table webauthn_credentials
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table webauthn_credentials
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}