package com.jp.login.entity;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table webauthn_credentials
 */
@Data
public class WebauthnCredentialsWithBLOBs extends WebauthnCredentials {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webauthn_credentials.public_key_cose
     *
     * @mbg.generated
     */
    private byte[] publicKeyCose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column webauthn_credentials.user_handle
     *
     * @mbg.generated
     */
    private byte[] userHandle;
}