name: Deploy and Run Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      # リポジトリからコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Mavenのインストール
      - name: Install Maven
        run: |
          mkdir -p /usr/local/apache-maven
          curl -sSL https://apache.osuosl.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz | sudo tar -xz -C /usr/local/apache-maven --strip-components=1
          ln -s /usr/local/apache-maven/bin/mvn /usr/bin/mvn

      # Mavenのインストール確認
      - name: Verify Maven Installation
        run: |
          mvn -version

      # MavenでSpring Bootアプリケーションをビルド
      - name: Build JAR with Maven
        run: |
          mvn clean package -DskipTests

      # ビルドされたJARファイルを実行
      - name: Run JAR on Rocky Linux
        run: |
          ps aux | grep 'java -jar target/demo-0.0.1-SNAPSHOT.jar' | grep -v grep | awk '{print $2}' | xargs -r kill || true
          nohup java -jar target/demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &